# Generated by Django 5.2.8 on 2025-11-25 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='grupos_unidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
